steps:
  ###############################
  # Main Web App Build & Deploy #
  ###############################
  
  # Install dependencies for main app
  - name: 'node:20'
    id: 'main-install'
    entrypoint: npm
    args: ['ci']

  # Build the Next.js application
  - name: 'node:20'
    id: 'main-build'
    entrypoint: npm
    args: ['run', 'build']
    env:
      - 'PROJECT_ID=${PROJECT_ID}'
      - 'REGION=${_REGION}'
      - 'NEXT_PUBLIC_TWITCH_CLIENT_ID=${_TWITCH_CLIENT_ID}'
      - 'TWITCH_CLIENT_SECRET=${_TWITCH_CLIENT_SECRET}'
      - 'NEXTAUTH_SECRET=${_NEXTAUTH_SECRET}'
      - 'NEXTAUTH_URL=${_NEXTAUTH_URL}'

  # Build and push the container image for main app
  - name: 'gcr.io/cloud-builders/docker'
    id: 'main-container-build'
    args:
      - 'build'
      - '-t'
      - '${_REGION}-docker.pkg.dev/${PROJECT_ID}/${_REPOSITORY}/${_MAIN_SERVICE_NAME}'
      - '--build-arg'
      - 'PROJECT_ID=${PROJECT_ID}'
      - '--build-arg'
      - 'REGION=${_REGION}'
      - '--build-arg'
      - 'NEXTAUTH_SECRET=${_NEXTAUTH_SECRET}'
      - '--build-arg'
      - 'NEXTAUTH_URL=${_NEXTAUTH_URL}'
      - '--build-arg'
      - 'NEXT_PUBLIC_TWITCH_CLIENT_ID=${_TWITCH_CLIENT_ID}'
      - '--build-arg'
      - 'TWITCH_CLIENT_SECRET=${_TWITCH_CLIENT_SECRET}'
      - '.'

  # Push the container image for main app
  - name: 'gcr.io/cloud-builders/docker'
    id: 'main-container-push'
    args:
      - 'push'
      - '${_REGION}-docker.pkg.dev/${PROJECT_ID}/${_REPOSITORY}/${_MAIN_SERVICE_NAME}'

  # Deploy main app to Cloud Run
  - name: 'gcr.io/cloud-builders/gcloud'
    id: 'main-deploy'
    args:
      - 'run'
      - 'deploy'
      - '${_MAIN_SERVICE_NAME}'
      - '--image'
      - '${_REGION}-docker.pkg.dev/${PROJECT_ID}/${_REPOSITORY}/${_MAIN_SERVICE_NAME}'
      - '--region'
      - '${_REGION}'
      - '--platform'
      - 'managed'
      - '--allow-unauthenticated'
      - '--set-env-vars'
      - 'PROJECT_ID=${PROJECT_ID},REGION=${_REGION},NEXT_PUBLIC_TWITCH_CLIENT_ID=${_TWITCH_CLIENT_ID},TWITCH_CLIENT_SECRET=${_TWITCH_CLIENT_SECRET},NEXTAUTH_SECRET=${_NEXTAUTH_SECRET},NEXTAUTH_URL=${_NEXTAUTH_URL}'

  #################################
  # EventSub Service Build & Deploy #
  #################################
  
  # Build the container image for EventSub service
  - name: 'gcr.io/cloud-builders/docker'
    id: 'eventsub-container-build'
    args: 
      - 'build'
      - '-t'
      - '${_REGION}-docker.pkg.dev/${PROJECT_ID}/${_REPOSITORY}/${_EVENTSUB_SERVICE_NAME}'
      - './eventsub-service'

  # Push the container image for EventSub service
  - name: 'gcr.io/cloud-builders/docker'
    id: 'eventsub-container-push'
    args: 
      - 'push'
      - '${_REGION}-docker.pkg.dev/${PROJECT_ID}/${_REPOSITORY}/${_EVENTSUB_SERVICE_NAME}'

  # Deploy EventSub service to Cloud Run
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    id: 'eventsub-deploy'
    entrypoint: gcloud
    args:
      - 'run'
      - 'deploy'
      - '${_EVENTSUB_SERVICE_NAME}'
      - '--image'
      - '${_REGION}-docker.pkg.dev/${PROJECT_ID}/${_REPOSITORY}/${_EVENTSUB_SERVICE_NAME}'
      - '--region'
      - '${_REGION}'
      - '--platform'
      - 'managed'
      - '--min-instances'
      - '1'
      - '--max-instances'
      - '3'
      - '--cpu'
      - '1'
      - '--memory'
      - '512Mi'
      - '--timeout'
      - '300s'
      - '--startup-cpu-boost'
      - '--startup-cpu-percentage'
      - '100'
      - '--container-healthcheck'
      - 'initial-delay=10s,timeout=5s,path=/health'
      - '--set-env-vars'
      - 'TWITCH_CLIENT_ID=${_TWITCH_CLIENT_ID},TWITCH_CLIENT_SECRET=${_TWITCH_CLIENT_SECRET},PROJECT_ID=${PROJECT_ID},API_BASE_URL=${_API_BASE_URL}'

images:
  - '${_REGION}-docker.pkg.dev/${PROJECT_ID}/${_REPOSITORY}/${_MAIN_SERVICE_NAME}'
  - '${_REGION}-docker.pkg.dev/${PROJECT_ID}/${_REPOSITORY}/${_EVENTSUB_SERVICE_NAME}'

substitutions:
  _REGION: us-east1
  _REPOSITORY: trkv-web
  _MAIN_SERVICE_NAME: trkv-web
  _EVENTSUB_SERVICE_NAME: eventsub-service
  _API_BASE_URL: https://trkv-web-tk2q2v2qbq-ue.a.run.app

options:
  logging: CLOUD_LOGGING_ONLY
  dynamic_substitutions: true 