substitutions:
  _REGION: us-east1
  _REPOSITORY: trkv-web
  _SERVICE_NAME: trkv-web
  _DATABASE_URL: "https://firestore.googleapis.com/v1/projects/97822713735/databases/(default)/documents"
  _DISCORD_WEBHOOK_URL: "https://discord.com/api/webhooks/1349536487598719110/PDr2_Up1IwxxkF3OQWWX8Lx9RePOCjqVbNb5vqtBD2DgbuHI7Z0achw5ryEA8UpMdhhW"
  _NEXTAUTH_SECRET: "Fcbx2ThHEuyFhnku73Vvbi1ictIAvLKS"
  _NEXTAUTH_URL: "https://trkv-web-97822713735.us-east1.run.app"
  _NEXT_PUBLIC_TWITCH_CLIENT_ID: "h9thyt8t4vr25y9husyppryc5qrmxi"
  _TWITCH_CLIENT_SECRET: "io6r5cmxazlinsfnie1bridndzahds"
  _NOTIFICATION_EMAIL: "dallasg@gmail.com" 